### ISSUE TITLE
Clean Up Basic Next.js Application

### ISSUE THREAD

**Issue by ThomasCode92** [hardRockWorld/bab-online-shop#2]
The objective of this task is to conduct a comprehensive cleanup of our Next.js application to eliminate any unused content, CSS rules, assets, and other unnecessary elements. This cleanup initiative is intended to enhance the maintainability of the codebase, reduce file size, and ensure that we begin from a clean slate.

## Tasks
1. Identify Unused Content
2. Remove Unused Content
3. Identify and Eliminate Unused elements

## Additional Notes
* Create a dedicated branch for this cleanup task to isolate changes from the main codebase.
* Document significant changes made during the cleanup process through through comments or commit messages.
* Ensure that the cleanup process does not inadvertently remove critical functionality or disrupt existing features.
* Upon completion of the cleanup and successful testing, initiate a pull request for review and merge it into the main branch after receiving approval.

## End Goal
The application should render a blank page with just a (unstyled) title

**Comment by hardRockWorld** [comment]
<img width="196" alt="Code_BojfJNNWUY" src="https://github.com/hardRockWorld/bab-online-shop/assets/82425081/a11aed49-49fd-4161-868a-212a7590b143">
 do I need to put ".vscode/" inside the gitignore file?

**Comment by ThomasCode92** [comment]
You can decide whether to include the ".vscode/" directory in the repository. Typically, it's not committed in most projects. However, if you'd like to share your settings and configurations with others, you can leave it in.

Perhaps it's best to keep it in for now so I can share my settings. Later on, if you decide to use your own configuration, you can choose to ignore it in Git.

**Comment by hardRockWorld** [comment]
@ThomasCode92 :
do we need to keep these files, like the favicon.ico, img, etc?

<img width="960" alt="Code_YnIvr01fM4" src="https://github.com/hardRockWorld/bab-online-shop/assets/82425081/93b2691d-e8e8-4bc8-8787-63daacc1fa0b">

**Comment by hardRockWorld** [comment]
@ThomasCode92 :
After I cleaned up the project folder and removed unnecessary file and run the dev server, I am getting this error in the browser inspect.

<img width="960" alt="msedge_NU9WrGee9X" src="https://github.com/hardRockWorld/bab-online-shop/assets/82425081/1463a89f-c4b9-4528-87bb-5933ad1cc90d">

**Comment by ThomasCode92** [comment]
Can you link your branch to the issue?
Then I can check it out and take a look

**Comment by ThomasCode92** [comment]
I've tried it out, and it appears to be working fine on my computer with both Firefox and Chrome. Are any browser extensions activated on your end? It's possible that one of them might be triggering the error. Have you encountered this error on other websites too?

**Comment by hardRockWorld** [comment]
> I've tried it out, and it appears to be working fine on my computer with both Firefox and Chrome. Are any browser extensions activated on your end? It's possible that one of them might be triggering the error. Have you encountered this error on other websites too?

yes, I have browser extension enabled, maybe you are right, it's because of the browser extension errors. I will remove these extensions like adblocker, etc

**Comment by hardRockWorld** [comment]
Could you please check the latest commit and updated README.md file, please advise if i need to add some more tech options in the project description.
